# -*- coding: utf-8 -*-
"""Red_Bitcoin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I-Ru6NoqIxkSkUhs3EkNlhPTlfjsggXE
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# -------------------------
# 1. Cargar datos
# -------------------------
data = [
(4,"11:36"), (1,"10:58"), (1,"11:04"), (1,"17:09"), (1,"18:35"),
(1,"18:41"), (1,"19:54"), (1,"20:08"), (2,"4:30"), (2,"4:39"),
(2,"4:40"), (2,"4:59"), (2,"7:41"), (2,"4:49"), (2,"8:06"),
(2,"8:10"), (2,"8:57"), (2,"9:03"), (2,"9:07"), (2,"10:11"),
(2,"14:47"), (2,"17:57"), (2,"18:36"), (2,"18:48"), (2,"19:20"),
(3,"7:37"), (3,"7:42"), (3,"8:11"), (3,"8:36"), (3,"8:57"),
(3,"12:24"), (3,"12:26"), (3,"12:58"), (3,"13:02"),
(3,"17:23"), (3,"18:36"), (3,"18:51"), (3,"19:10"),
(4,"7:34"), (4,"7:35"), (4,"7:36"), (4,"7:53"), (4,"7:57"),
(4,"8:13"), (4,"8:18"), (4,"8:20"), (4,"10:01"),
(4,"10:10"), (4,"10:24"), (4,"10:31"), (4,"10:49"),
(4,"12:06"), (4,"12:08"), (4,"12:09"), (4,"12:34"),
(4,"12:47"), (4,"13:25"), (4,"15:13"), (4,"17:04"),
(5,"14:39"), (5,"14:40"), (6,"19:42"), (6,"19:46"), (6,"19:49"),
(7,"7:01"), (7,"16:05"), (7,"16:28"), (7,"16:32"),
(1,"7:40"), (1,"17:19"), (2,"8:35"), (2,"8:41"), (2,"9:07"), (2,"9:11"), (2,"9:13"),
(2,"10:19"), (2,"10:58"), (2,"11:37"), (2,"12:34"), (2,"12:50"),
(2,"16:22"), (3,"7:33"), (3,"7:35"), (3,"7:36"), (3,"7:45"), (3,"7:49"),
(3,"8:08"), (3,"9:08"), (3,"9:33"), (3,"9:35"),(3,"10:43"), (3,"10:45"),
(3,"14:03"), (3,"14:09"), (3,"14:14"),(3,"20:49"), (3,"20:54"), (3,"22:50"),
(4,"7:32"), (4,"7:37"), (4,"7:39"), (4,"7:43"),
(4,"8:19"), (4,"8:20"),(4,"8:57"), (4,"8:58"),
(4,"9:30"),(4,"10:15"), (4,"10:25"), (4,"10:30"),
(4,"10:53"), (4,"10:55"),(4,"11:16"),(4,"12:20"),(4,"14:04"),(4,"15:22"),
(5,"3:33"), (5,"3:37"), (5,"4:33"),(5,"6:39"), (5,"6:40"),
(5,"7:28"),(5,"8:56"), (5,"9:05"), (5,"9:06"), (5,"9:28"), (5,"9:45"),
(5,"10:43"), (5,"10:53"), (5,"10:56"),(5,"11:14"), (5,"11:22"), (5,"11:27"),
(5,"12:03"), (5,"12:07"), (5,"12:13"),(5,"14:11"),(6,"4:11"),
(7,"1:25"),   (7,"1:26"),   (7,"6:11"),   (7,"9:37"),   (7,"9:39"),
(7,"10:58"),  (7,"11:02"),  (7,"11:08"),  (7,"11:09"),  (7,"11:55"),
(7,"15:55"),  (7,"16:06"),  (7,"17:04"),  (1,"1:55"),   (1,"1:56"),
(1,"6:43"),   (1,"7:20"),   (1,"7:52"),   (1,"8:42"),   (1,"8:53"),
(1,"9:04"),   (1,"9:05"),   (1,"9:08"),   (1,"9:50"),   (1,"10:27"),
(2,"7:36"),   (2,"7:38"),   (2,"7:40"),   (2,"8:04"),   (2,"8:07"),
(2,"8:49"),   (2,"9:00"),   (2,"9:04"),   (2,"9:06"),   (2,"10:45"),
(2,"11:07"),  (2,"13:45"),  (2,"13:47"),  (2,"18:17"),  (2,"21:17"),
(3,"0:02"),   (3,"6:24"),   (3,"7:37"),   (3,"8:20"),   (3,"9:26"),
(3,"9:27"),   (3,"10:44"),  (3,"10:45"),  (3,"10:46"),  (3,"18:17"),
(3,"18:49"),  (3,"20:43"),  (4,"4:08"),   (4,"6:17"),   (4,"7:38"),
(4,"10:15"),  (4,"11:03"),  (4,"11:11"),  (4,"11:21"),  (4,"11:42"),
(4,"11:43"),  (4,"14:01"),  (4,"21:26"),  (4,"21:27"),  (4,"21:35"),
(5,"7:48"),   (5,"8:03"),   (5,"8:04"),   (5,"8:08"),   (5,"9:09"),
(5,"9:10")
]

df = pd.DataFrame(data, columns=["day", "time"])


# -------------------------
# 2. Feature engineering
# -------------------------
def time_to_minutes(t):
    h, m = map(int, t.split(":"))
    return h * 60 + m

df["minutes"] = df["time"].apply(time_to_minutes)

# Variables cíclicas (muy importante)
df["hour_sin"] = np.sin(2 * np.pi * df["minutes"] / 1440)
df["hour_cos"] = np.cos(2 * np.pi * df["minutes"] / 1440)

df["day_sin"] = np.sin(2 * np.pi * df["day"] / 7)
df["day_cos"] = np.cos(2 * np.pi * df["day"] / 7)

df["target"] = 1  # oportunidades observadas

# -------------------------
# 3. Generar datos negativos
# -------------------------
np.random.seed(42)
neg_samples = 200

neg_day = np.random.randint(1, 8, neg_samples)
neg_min = np.random.randint(0, 1440, neg_samples)

neg_df = pd.DataFrame({
    "day": neg_day,
    "minutes": neg_min,
    "target": 0
})

neg_df["hour_sin"] = np.sin(2 * np.pi * neg_df["minutes"] / 1440)
neg_df["hour_cos"] = np.cos(2 * np.pi * neg_df["minutes"] / 1440)
neg_df["day_sin"] = np.sin(2 * np.pi * neg_df["day"] / 7)
neg_df["day_cos"] = np.cos(2 * np.pi * neg_df["day"] / 7)

# Unir dataset
df_all = pd.concat([df, neg_df])

X = df_all[["hour_sin", "hour_cos", "day_sin", "day_cos"]]
y = df_all["target"]

# -------------------------
# 4. Escalamiento
# -------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# -------------------------
# 5. Modelo NN
# -------------------------
model = MLPClassifier(hidden_layer_sizes=(10, 10),
                      activation='relu',
                      max_iter=1000)

model.fit(X_scaled, y)

# -------------------------
# 6. UI Streamlit
# -------------------------
st.title("📈 Bitcoin Trading Opportunity Predictor")

st.write("Predicción basada en día y hora")

day = st.slider("Día de la semana (1=Lunes, 7=Domingo)", 1, 7, 3)
hour = st.slider("Hora", 0, 23, 12)
minute = st.slider("Minuto", 0, 59, 0)

minutes = hour * 60 + minute

# Transformación
input_data = np.array([[
    np.sin(2 * np.pi * minutes / 1440),
    np.cos(2 * np.pi * minutes / 1440),
    np.sin(2 * np.pi * day / 7),
    np.cos(2 * np.pi * day / 7)
]])

input_scaled = scaler.transform(input_data)

# Predicción
prob = model.predict_proba(input_scaled)[0][1]

st.subheader("📊 Probabilidad de oportunidad:")
st.write(f"{prob:.2%}")

if prob > 0.6:
    st.success("🔥 Alta probabilidad de trading")
elif prob > 0.4:
    st.warning("⚠️ Probabilidad media")
else:
    st.error("❌ Baja probabilidad")
