# -*- coding: utf-8 -*-
"""Red_Bitcoin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I-Ru6NoqIxkSkUhs3EkNlhPTlfjsggXE
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# -------------------------
# 1. Cargar datos
# -------------------------
data = [
(5,"16:31"), (7,"11:15"), (7,"11:25"), (1,"12:46"), (1,"13:06"),
(2,"10:47"), (2,"11:47"), (4,"18:42"), (5,"19:13"), (5,"20:03"),
(5,"20:13"), (5,"21:23"), (5,"21:53"), (5,"21:39"), (1,"19:07"),
(1,"19:42"), (1,"19:52"), (2,"7:33"), (2,"7:58"), (5,"7:52"),
(5,"8:12"), (5,"8:37"), (5,"17:58"), (6,"22:04"), (7,"0:04"),
(7,"0:30"), (7,"0:45"), (7,"3:05"), (1,"10:01"), (1,"10:11"),
(1,"10:41"), (1,"10:56"), (1,"10:57"), (1,"16:07"), (5,"7:57"),
(5,"8:52"), (1,"22:51"), (1,"23:22"), (3,"0:08"), (3,"6:48"),
(3,"7:13"), (3,"8:33"), (2,"10:32"), (2,"11:02"), (2,"12:07"),
(2,"13:47"), (2,"14:02"), (2,"15:57"), (3,"14:53"), (3,"15:08"),
(3,"16:04"), (3,"17:04"), (5,"5:36"), (5,"23:12"), (5,"9:52"),
(5,"10:17"), (5,"10:32"), (7,"11:19"), (7,"12:45"), (7,"13:05"),
(7,"13.2"), (7,"14:40"), (7,"17:30"), (1,"6:56"), (3,"23:24"),
(4,"10:05"), (4,"10:35"), (4,"10:50"), (4,"13:30"), (4,"13:40"),
(4,"15:00"), (5,"6:31"), (5,"6:46"), (3,"3:43"), (3,"9:24"),
(4,"0:10"), (4,"0:55"), (4,"1:55"), (4,"2:35"), (4,"6:40"),
(5,"9:02"), (5,"9:12"), (5,"10:12"), (5,"10:27"), (5,"11:42"),
(5,"12:52"), (7,"18:30"), (1,"18:06"), (2,"7:47"), (2,"8:32"),
(2,"8:57"), (2,"12:37"), (2,"13:02"), (2,"13:32"), (2,"14:22"),
(2,"15:52"), (5,"11:01"), (6,"11:02"), (6,"11:12"), (6,"14:18"),
(6,"15:13"), (1,"5:00"), (1,"6:00"), (1,"6:30"), (1,"7:00"),
(1,"7:35"), (1,"7:55"), (1,"8:40"), (1,"9:00"), (1,"9:25"),
(1,"10:05"), (2,"7:26"), (2,"8:02"), (2,"8:42"), (2,"9:52"),
(3,"18:48"), (3,"19:44"), (3,"20:09"), (5,"6:16"), (5,"7:01"),
(5,"7:21"), (5,"7:56"), (5,"8:11"), (5,"9:36"), (1,"8:20"),
(1,"8:30"), (1,"9:00"), (1,"9:15"), (1,"10:05"), (1,"11:10"),
(1,"12:40"), (1,"13:00"), (1,"14:00"), (1,"15:55"), (2,"9:26"),
(2,"9:56"), (3,"8:17"), (4,"1:28"), (4,"1:59"), (5,"10:26"),   
]

df = pd.DataFrame(data, columns=["day", "time"])


# -------------------------
# 2. Feature engineering
# -------------------------
def time_to_minutes(t):
    h, m = map(int, t.split(":"))
    return h * 60 + m

df["minutes"] = df["time"].apply(time_to_minutes)

# Variables cíclicas (muy importante)
df["hour_sin"] = np.sin(2 * np.pi * df["minutes"] / 1440)
df["hour_cos"] = np.cos(2 * np.pi * df["minutes"] / 1440)

df["day_sin"] = np.sin(2 * np.pi * df["day"] / 7)
df["day_cos"] = np.cos(2 * np.pi * df["day"] / 7)

df["target"] = 1  # oportunidades observadas

# -------------------------
# 3. Generar datos negativos
# -------------------------
np.random.seed(42)
neg_samples = 200

neg_day = np.random.randint(1, 8, neg_samples)
neg_min = np.random.randint(0, 1440, neg_samples)

neg_df = pd.DataFrame({
    "day": neg_day,
    "minutes": neg_min,
    "target": 0
})

neg_df["hour_sin"] = np.sin(2 * np.pi * neg_df["minutes"] / 1440)
neg_df["hour_cos"] = np.cos(2 * np.pi * neg_df["minutes"] / 1440)
neg_df["day_sin"] = np.sin(2 * np.pi * neg_df["day"] / 7)
neg_df["day_cos"] = np.cos(2 * np.pi * neg_df["day"] / 7)

# Unir dataset
df_all = pd.concat([df, neg_df])

X = df_all[["hour_sin", "hour_cos", "day_sin", "day_cos"]]
y = df_all["target"]

# -------------------------
# 4. Escalamiento
# -------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# -------------------------
# 5. Modelo NN
# -------------------------
model = MLPClassifier(hidden_layer_sizes=(10, 10),
                      activation='relu',
                      max_iter=1000)

model.fit(X_scaled, y)

# -------------------------
# 6. UI Streamlit
# -------------------------
st.image("NQH.svg", caption="", width=400)

st.markdown(
    '<h1 style="color:#FFFFFF;">Bitcoin Trading Opportunity Predictor</h1>',
    unsafe_allow_html=True
)
st.markdown(
    '<h2 style="color:#FFFFFF;">Predicción basada en día y hora</h2>',
    unsafe_allow_html=True
)


day = st.slider("Día de la semana (1=Lunes, 7=Domingo)", 1, 7, 3)
hour = st.slider("Hora", 0, 23, 12)
st.markdown("""
<style>
div[data-testid="stSlider"] label {
    color: white !important;
}
</style>
""", unsafe_allow_html=True)
minute = st.slider("Minuto", 0, 59, 0)

minutes = hour * 60 + minute

# Transformación
input_data = np.array([[
    np.sin(2 * np.pi * minutes / 1440),
    np.cos(2 * np.pi * minutes / 1440),
    np.sin(2 * np.pi * day / 7),
    np.cos(2 * np.pi * day / 7)
]])

input_scaled = scaler.transform(input_data)

# Predicción
prob = model.predict_proba(input_scaled)[0][1]

st.markdown(
    '<h2 style="color:#FFFFFF;">Probabilidad de oportunidad: </h2>',
    unsafe_allow_html=True
)
st.markdown(
    f'<span style="color:white;">**{prob:.2%}**</span>',
    unsafe_allow_html=True
)
if prob > 0.6:
    st.success("🔥 Alta probabilidad de trading")
elif prob > 0.4:
    st.warning("⚠️ Probabilidad media")
else:
    st.error("❌ Baja probabilidad")


####################
st.markdown(
    f'<span style="color:#F1F5F9;">**Powored by**</span>',
    unsafe_allow_html=True
)
st.image("NQH.svg", caption="", width=200)

# -----------------------------------------------------
st.markdown("""
<style>
    .stApp {
        background-color: #0F172A;
    }
    h1, h2, h3 {
        color: #FFFFFF;
    }
</style>
""", unsafe_allow_html=True)
